create PROCEDURE game_record_truncate AS
  BEGIN
    -- All DDL statements in Oracle PL/SQL should use Execute Immediate before the statement. Hence you should use:
    execute immediate '
    TRUNCATE TABLE BULL2_BET_CONFIRM
    PRESERVE MATERIALIZED VIEW LOG
    REUSE STORAGE;

    TRUNCATE TABLE BULL2_BET_CONFIRM_DETAIL
    PRESERVE MATERIALIZED VIEW LOG
    REUSE STORAGE;

    TRUNCATE TABLE BULL2_BET_RESULT
    PRESERVE MATERIALIZED VIEW LOG
    REUSE STORAGE;

    TRUNCATE TABLE BULL2_BET_RESULT_DETAIL
    PRESERVE MATERIALIZED VIEW LOG
    REUSE STORAGE;

    TRUNCATE TABLE BULL2_GAME
    PRESERVE MATERIALIZED VIEW LOG
    REUSE STORAGE;


    TRUNCATE TABLE ROULETTE_BET_CONFIRM
    PRESERVE MATERIALIZED VIEW LOG
    REUSE STORAGE;


    TRUNCATE TABLE ROULETTE_BET_CONFIRM_DETAIL
    PRESERVE MATERIALIZED VIEW LOG
    REUSE STORAGE;


    TRUNCATE TABLE ROULETTE_BET_RESULT
    PRESERVE MATERIALIZED VIEW LOG
    REUSE STORAGE;


    TRUNCATE TABLE ROULETTE_BET_RESULT_DETAIL
    PRESERVE MATERIALIZED VIEW LOG
    REUSE STORAGE;

    TRUNCATE TABLE ROULETTE_GAME
    PRESERVE MATERIALIZED VIEW LOG
    REUSE STORAGE;';
  END;
/
